language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - ./mvnw clean install -Dmaven.test.skip=true
  - cd spring-gradle-projects && ./gradlew build
after_success:
  - cd .. && ./mvnw clean test -Dmaven.test.failure.ignore=true jacoco:report coveralls:report
